language: python

python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'

sudo: false

env:
  PYTHONPATH: resources/lib:tests
  PYTHONIOENCODING: utf-8

install:
- pip install -r requirements.txt

script:
- tox
- tox -e flake8
- pylint resources/lib/ tests/
- msgcmp resources/language/resource.language.{nl_nl,en_gb}/strings.po
#- kodi-addon-checker . --branch=krypton
#- kodi-addon-checker . --branch=leia
- proxy.py &
- coverage run -m unittest discover
- coverage run -a resources/lib/service_entry.py
- coverage run -a tests/run.py /

after_success:
- codecov
